### ISSUE TITLE
Support iOS7

### ISSUE THREAD

**Issue by wtmoose** [robrix/Box#25]
Some of us poor souls are forced to support iOS7. Bumping the deployment target down to 7.0 would bring a little joy into our otherwise miserable existence.

**Comment by robrix** [comment]
I don’t think it would, unfortunately, since iOS 7 doesn’t support dynamic frameworks.

AIUI Swift doesn’t support static libraries, either, so I guess that leaves using Box as a submodule and adding Box.swift & BoxType.swift to your target.

You can do that today, so I’m not sure that there’s any action for us to take here.

**Comment by wtmoose** [comment]
What I'm doing with other Swift frameworks is including them as submodules and adding their projects as dependencies/static libraries.

Your suggestion of adding the source files to the project will probably be fine since you only have 2 files, but this doesn't work well with larger projects that may be adding and removing files over time.

Tim

**Comment by robrix** [comment]
@wtmoose rdar://17181019 — Xcode does not support building static libraries with Swift. If Xcode doesn’t support it, I can’t support it. Sorry :confused:

**Comment by wtmoose** [comment]
Gotcha. Thanks for the explanation. My setup is working in Simulator with other Swift libraries, but it sounds like I need to go back to the drawing board.
